In [1]:
import sys
sys.path.append('..')

In [2]:
import pandas as pd
from sklearn.datasets import fetch_california_housing
from Regression.Regression import StandardScaler, TrainTestSplit, SimpleRegression

In [3]:
california = fetch_california_housing()

In [4]:
california

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib:\nhttps://lib.stat.cmu.edu/datasets/houses.zip\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [5]:
california.target_names

['MedHouseVal']

In [6]:
pd.DataFrame(california.data, columns=california.feature_names).shape

(20640, 8)

In [7]:
df = pd.DataFrame(california.data, columns=california.feature_names)
df[california.target_names[0]] = california.target
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [8]:
x = df.drop('MedHouseVal', axis=1)
x

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [9]:
y = df['MedHouseVal']
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [10]:
model = TrainTestSplit()

In [11]:
x_train, y_train, x_test, y_test = model.split(x, y)

In [12]:
x_train

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
4553,1.1979,33.0,2.020725,1.031088,435.0,2.253886,34.06,-118.24
12286,1.6250,1.0,3.000000,1.000000,8.0,4.000000,33.86,-116.95
17333,5.2990,12.0,7.214932,1.047511,1200.0,2.714932,34.91,-120.44
17442,3.0081,5.0,4.699029,1.135922,1302.0,2.106796,34.66,-120.46
9628,2.0000,17.0,7.289157,1.915663,416.0,5.012048,37.31,-120.35
...,...,...,...,...,...,...,...,...
12618,4.2075,15.0,6.111334,1.054162,2415.0,2.422267,38.50,-121.54
6356,3.9464,9.0,4.675258,1.067010,619.0,3.190722,34.14,-117.96
10615,6.7962,4.0,6.205937,1.024119,1525.0,2.829314,33.67,-117.80
18600,5.5785,17.0,6.200000,1.229787,591.0,2.514894,37.15,-122.18
4134,3.3542,52.0,4.882716,1.074074,501.0,3.092593,34.13,-118.22

In [13]:
x_test

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
8,2.0804,42.0,4.294118,1.117647,1206.0,2.026891,37.84,-122.26
12,3.0750,52.0,5.322650,1.012821,1098.0,2.346154,37.85,-122.26
13,2.6736,52.0,4.000000,1.097701,345.0,1.982759,37.84,-122.26
15,2.1250,50.0,4.242424,1.071970,697.0,2.640152,37.85,-122.26
...,...,...,...,...,...,...,...,...
20623,2.8235,32.0,5.101322,1.074890,598.0,2.634361,39.03,-121.37
20627,3.0000,5.0,6.067797,1.101695,169.0,2.864407,39.13,-121.32
20629,2.0943,28.0,5.519802,1.020902,6912.0,3.801980,39.12,-121.39
20630,3.5673,11.0,5.932584,1.134831,1257.0,2.824719,39.29,-121.32
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09

In [14]:
y_train

4553     3.500
12286    0.550
17333    2.268
17442    1.352
9628     0.875
         ...
12618    1.836
6356     1.796
10615    3.291
18600    2.841
4134     1.781
Name: MedHouseVal, Length: 14448, dtype: float64

In [15]:
y_test

2        3.521
8        2.267
12       2.135
13       1.913
15       1.400
         ...
20623    0.655
20627    1.625
20629    1.083
20630    1.120
20635    0.781
Name: MedHouseVal, Length: 6192, dtype: float64

In [16]:
scalar = StandardScaler()
x_train_scaled = scalar.fit(x_train)
x_train_scaled

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
4553,-1.397850,0.340252,-1.474809,-0.138753,-0.864954,-0.117978,-0.735365,0.663315
12286,-1.173486,-2.208654,-1.048209,-0.206772,-1.238819,0.147325,-0.828932,1.307666
17333,0.756542,-1.332468,0.787936,-0.102820,-0.195149,-0.047927,-0.337703,-0.435579
17442,-0.446915,-1.890041,-0.308063,0.090618,-0.105841,-0.140326,-0.454662,-0.445569
9628,-0.976490,-0.934201,0.820270,1.796644,-0.881589,0.301094,0.785105,-0.390625
...,...,...,...,...,...,...,...,...
12618,0.183154,-1.093508,0.307177,-0.088268,0.868659,-0.092394,1.341831,-0.985026
6356,0.045993,-1.571428,-0.318419,-0.060157,-0.703850,0.024364,-0.697938,0.803174
10615,1.543051,-1.969694,0.348389,-0.154002,0.089409,-0.030548,-0.917821,0.883093
18600,0.903369,-0.934201,0.345802,0.295989,-0.728366,-0.078320,0.710251,-1.304705
4134,-0.265101,1.853666,-0.228044,-0.044702,-0.807167,0.009454,-0.702616,0.673305

In [17]:
SR = SimpleRegression()
SR.fit(x_train_scaled, y_train)

Current MSE: 5.596813950517032
5.596813950517032
Current MSE: 5.399462329460518
-0.19735162105651405
Current MSE: 5.210032426507832
-0.18942990295268647
Current MSE: 5.02820146233578
-0.18183096417205213
Current MSE: 4.85366010051819
-0.17454136181758972
Current MSE: 4.686111867276709
-0.16754823324148127
Current MSE: 4.525272597706405
-0.16083926957030314
Current MSE: 4.370869907170915
-0.15440269053549027
Current MSE: 4.222642686632505
-0.1482272205384101
Current MSE: 4.080340620748886
-0.14230206588361938
Current MSE: 3.9437237276310886
-0.13661689311779712
Current MSE: 3.8125619192155877
-0.13116180841550085
Current MSE: 3.686634581259221
-0.1259273379563668
Current MSE: 3.5657301720176298
-0.12090440924159118
Current MSE: 3.449645838717109
-0.11608433330052081
Current MSE: 3.33818705097602
-0.11145878774108908
Current MSE: 3.2311672503756643
-0.10701980060035554
Current MSE: 3.1284075154216047
-0.10275973495405966
Current MSE: 3.0297362411753412
-0.09867127424626343
Current MSE: 2.934988832872856
-0.09474740830248507
Current MSE: 2.844007412881176
-0.0909814199916803
Current MSE: 2.756640540376754
-0.08736687250442188
Current MSE: 2.6727429431603733
-0.08389759721638068
Current MSE: 2.592175261052403
-0.08056768210797038
Current MSE: 2.5148038003398407
-0.07737146071256218
Current MSE: 2.440500298772632
-0.07430350156720866
Current MSE: 2.3691417006314155
-0.07135859814121659
Current MSE: 2.3006099414121683
-0.06853175921924715
Current MSE: 2.234791741695334
-0.06581819971683434
Current MSE: 2.1715784097878794
-0.0632133319074546
Current MSE: 2.1108656527465715
-0.06071275704130796
Current MSE: 2.0525533954094874
-0.058312257337084006
Current MSE: 1.9965456070805734
-0.056007788328914065
Current MSE: 1.9427501355288979
-0.05379547155167552
Current MSE: 1.891078547980242
-0.05167158754865575
Current MSE: 1.8414459787938093
-0.04963256918643277
Current MSE: 1.7937709835312303
-0.04767499526257901
Current MSE: 1.747975399138675
-0.045795584392555266
Current MSE: 1.7039842099758522
-0.04399118916282285
Current MSE: 1.6617254194379676
-0.042258790537884616
Current MSE: 1.6211299269284096
-0.04059549250955796
Current MSE: 1.5821314099510326
-0.038998516977376996
Current MSE: 1.5446662111014586
-0.037465198849574
Current MSE: 1.508673229746853
-0.0359929813546056
Current MSE: 1.4740938181931753
-0.03457941155367772
Current MSE: 1.4408716821479735
-0.033222136045201855
Current MSE: 1.4089527852954271
-0.03191889685254634
Current MSE: 1.378285257808558
-0.030667527486869073
Current MSE: 1.3488193086313591
-0.029465949177198913
Current MSE: 1.320507141371015
-0.028312167260344134
Current MSE: 1.293302873647505
-0.027204267723510034
Current MSE: 1.2671624597546145
-0.026140413892890457
Current MSE: 1.2420436164928257
-0.025118843261788815
Current MSE: 1.2179057520406844
-0.024137864452141278
Current MSE: 1.194709897737094
-0.02319585430359039
Current MSE: 1.1724186426525516
-0.02229125508454244
Current MSE: 1.1509960708326614
-0.021422571819890157
Current MSE: 1.1304077011023248
-0.02058836973033662
Current MSE: 1.1106204293238477
-0.019787271778477056
Current MSE: 1.0916024730068077
-0.019017956317040063
Current MSE: 1.073323318171943
-0.01827915483486464
Current MSE: 1.0557536683755107
-0.017569649796432385
Current MSE: 1.0388653958045841
-0.01688827257092651
Current MSE: 1.0226314943575865
-0.016233901446997656
Current MSE: 1.0070260346280135
-0.015605459729572946
Current MSE: 0.9920241207128018
-0.015001913915211773
Current MSE: 0.9776018487701212
-0.014422271942680531
Current MSE: 0.9637362672545771
-0.013865581515544179
Current MSE: 0.9504053387608411
-0.01333092849373596
Current MSE: 0.9375879034096533
-0.012817435351187845
Current MSE: 0.9252636437129139
-0.012324259696739337
Current MSE: 0.9134130508572549
-0.011850592855659037
Current MSE: 0.9020173923480141
-0.011395658509240736
Current MSE: 0.8910586809579848
-0.010958711390029352
Current MSE: 0.880519644927625
-0.010539036030359772
Current MSE: 0.8703836993656514
-0.010135945561973614
Current MSE: 0.8606349188010657
-0.009748780564585724
Current MSE: 0.8512580108397005
-0.009376907961365144
Current MSE: 0.8422382908803243
-0.009019719959376227
Current MSE: 0.8335616578472108
-0.008676633033113501
Current MSE: 0.8252145708978627
-0.00834708694934816
Current MSE: 0.8171840270662929
-0.008030543831569759
Current MSE: 0.8094575398039006
-0.007726487262392334
Current MSE: 0.8020231183815468
-0.007434421422353732
Current MSE: 0.7948692481179411
-0.0071538702636056994
Current MSE: 0.7879848714008741
-0.006884376717066987
Current MSE: 0.7813593694692231
-0.006625501931651012
Current MSE: 0.7749825449249648
-0.006376824544258364
Current MSE: 0.7688446049456943
-0.006137939979270479
Current MSE: 0.7629361451693627
-0.005908459776331587
Current MSE: 0.7572481342240984
-0.005688010945264277
Current MSE: 0.7517718988770898
-0.0054762353470085845
Current MSE: 0.7464991097775734
-0.005272789099516451
Current MSE: 0.7414217677699838
-0.00507734200758958
Current MSE: 0.7365321907543059
-0.004889577015677937
Current MSE: 0.7318230010715987
-0.004709189682707171
Current MSE: 0.7272871133935626
-0.0045358876780361435
Current MSE: 0.7229177230958784
-0.004369390297684128
Current MSE: 0.7187082950958724
-0.00420942800000601
Current MSE: 0.714652553135848
-0.00405574196002445
Current MSE: 0.7107444694941879
-0.003908083641660065
Current MSE: 0.7069782551070507
-0.003766214387137201
Current MSE: 0.7033483500841861
-0.0036299050228646434
Current MSE: 0.6998494146030563
-0.0034989354811297835
Current MSE: 0.6964763201660955
-0.0033730944369607663
Current MSE: 0.6932241412065513
-0.0032521789595442163
Current MSE: 0.6900881470289353
-0.0031359941776160083
Current MSE: 0.6870637940706863
-0.003024352958248988
Current MSE: 0.6841467184721752
-0.0029170755985110652
Current MSE: 0.6813327289427157
-0.0028139895294595485
Current MSE: 0.6786177999107273
-0.0027149290319883335
Current MSE: 0.6759980649466896
-0.0026197349640377787
Current MSE: 0.6734698104479707
-0.0025282544987188516
Current MSE: 0.6710294695750642
-0.0024403408729065657
Current MSE: 0.668673616429181
-0.0023558531458831578
Current MSE: 0.6663989604615536
-0.002274655967627437
Current MSE: 0.664202341105192
-0.0021966193563615066
Current MSE: 0.662080722620211
-0.002121618484981047
Current MSE: 0.6600311891441933
-0.002049533476017662
Current MSE: 0.6580509399394101
-0.0019802492047832354
Current MSE: 0.6561372848290348
-0.001913655110375334
Current MSE: 0.6542876398148144
-0.001849645014220358
Current MSE: 0.6524995228689529
-0.001788116945861562
Current MSE: 0.6507705498932626
-0.0017289729756903016
Current MSE: 0.6490984308389092
-0.0016721190543533826
Current MSE: 0.647480965980349
-0.0016174648585601803
Current MSE: 0.6459160423373115
-0.001564923643037508
Current MSE: 0.6444016302389255
-0.0015144120983859866
Current MSE: 0.6429357800243255
-0.0014658502145999952
Current MSE: 0.6415166188743002
-0.001419161150025272
Current MSE: 0.6401423477687626
-0.0013742711055376722
Current MSE: 0.6388112385650304
-0.0013311092037321393
Current MSE: 0.6375216311921066
-0.0012896073729238289
Current MSE: 0.6362719309563404
-0.0012497002357662046
Current MSE: 0.6350606059540348
-0.0012113250023055855
Current MSE: 0.6338861845867443
-0.0011744213672905124
Current MSE: 0.632747253175176
-0.0011389314115682891
Current MSE: 0.6316424536677685
-0.0011047995074074946
Current MSE: 0.6305704814401859
-0.001071972227582596
Current MSE: 0.6295300831821057
-0.0010403982580802218
Current MSE: 0.6285200548678302
-0.0010100283142754352
Current MSE: 0.6275392398073899
-0.0009808150604403432
Current MSE: 0.6265865267749335
-0.0009527130324563649
Current MSE: 0.6256608482113373
-0.0009256785635962661
Current MSE: 0.6247611784980774
-0.0008996697132598319
Current MSE: 0.6238865322995373
-0.0008746461985401632
Current MSE: 0.6230359629710271
-0.0008505693285101312
Current MSE: 0.6222085610299064
-0.0008274019411207423
Current MSE: 0.6214034526872986
-0.0008051083426078298
Current MSE: 0.6206197984379954
-0.0007836542493031562
Current MSE: 0.6198567917062338
-0.0007630067317616618
Current MSE: 0.6191136575451311
-0.0007431341611026099
Current MSE: 0.6183896513876427
-0.000724006157488466
Current MSE: 0.6176840578470002
-0.0007055935406424796
Current MSE: 0.6169961895646615
-0.0006878682823386884
Current MSE: 0.6163253861038896
-0.0006708034607718627
Current MSE: 0.6156710128871465
-0.0006543732167431093
Current MSE: 0.6150324601755628
-0.0006385527115837508
Current MSE: 0.6144091420888149
-0.0006233180867478705
Current MSE: 0.6138004956638037
-0.0006086464250112389
Current MSE: 0.613205979950596
-0.0005945157132076773
Current MSE: 0.6126250751441511
-0.000580904806444904
Current MSE: 0.61205728175041
-0.0005677933937411339
Current MSE: 0.6115021197853855
-0.0005551619650244755
Current MSE: 0.6109591280059464
-0.0005429917794390615
Current MSE: 0.6104278631710331
-0.0005312648349132809
Current MSE: 0.6099078993321021
-0.0005199638389310479
Current MSE: 0.6093988271516395
-0.0005090721804625886
Current MSE: 0.6089002532486285
-0.0004985739030110015
Current MSE: 0.6084117995699045
-0.0004884536787239657
Current MSE: 0.6079331027863689
-0.00047869678353562595
Current MSE: 0.607463813713079
-0.00046928907328991354
Current MSE: 0.6070035967522652
-0.00046021696081377517
Current MSE: 0.6065521293583671
-0.0004514673938981195
Current MSE: 0.6061091015242169
-0.0004430278341501781
Current MSE: 0.6056742152875313
-0.00043488623668563875
Current MSE: 0.6052471842569066
-0.0004270310306246916
Current MSE: 0.6048277331565456
-0.0004194511003610124
Current MSE: 0.6044155973889721
-0.0004121357675734849
Current MSE: 0.6040105226150229
-0.0004050747739492433
Current MSE: 0.6036122643504311
-0.0003982582645917221
Current MSE: 0.6032205875783437
-0.0003916767720874015
Current MSE: 0.6028352663771427
-0.00038532120120104985
Current MSE: 0.6024560835629649
-0.0003791828141778142
Current MSE: 0.6020828303463353
-0.00037325321662962097
Current MSE: 0.601715306002358
-0.00036752434397724354
Current MSE: 0.6013533175539276
-0.0003619884484303837
Current MSE: 0.6009966794674436
-0.00035663808648400686
Current MSE: 0.6006452133605344
-0.0003514661069091707
Current MSE: 0.6002987477213172
-0.0003464656392172527
Current MSE: 0.5999571176387319
-0.0003416300825852536
Current MSE: 0.5996201645435184
-0.00033695309521353245
Current MSE: 0.5992877359594083
-0.00033242858411008935
Current MSE: 0.5989596852641333
-0.0003280506952749729
Current MSE: 0.5986358714598562
-0.000323813804277151
Current MSE: 0.5983161589526587
-0.00031971250719753375
Current MSE: 0.5980004173407191
-0.0003157416119395906
Current MSE: 0.5976885212108447
-0.0003118961298743672
Current MSE: 0.5973803499430225
-0.0003081712678222326
Current MSE: 0.5970757875226738
-0.0003045624203487085
Current MSE: 0.5967747223603069
-0.00030106516236683145
Current MSE: 0.5964770471182774
-0.0002976752420295048
Current MSE: 0.5961826585443716
-0.00029438857390584605
Current MSE: 0.5958914573119476
-0.00029120123242398765
Current MSE: 0.5956033478663715
-0.0002881094455761124
Current MSE: 0.5953182382774999
-0.00028510958887162374
Current MSE: 0.5950360400979741
-0.0002821981795257944
Current MSE: 0.5947566682270902
-0.00027937187088389326
Current MSE: 0.5944800407800285
-0.00027662744706169473
Current MSE: 0.5942060789622312
-0.0002739618177972636
Current MSE: 0.5939347069487216
-0.0002713720135095743
Current MSE: 0.5936658517681733
-0.0002688551805483108
Current MSE: 0.5933994431915388
-0.00026640857663451367
Current MSE: 0.5931354136250587
-0.000264029566480084
Current MSE: 0.5928736980074806
-0.000261715617578151
Current MSE: 0.5926142337113164
-0.0002594642961641913
Current MSE: 0.5923569604479849
-0.00025727326333147005
Current MSE: 0.59210182017668
-0.00025514027130491
Current MSE: 0.5918487570168227
-0.0002530631598572919
Current MSE: 0.5915977171639525
-0.00025103985287022734
Current MSE: 0.5913486488089232
-0.0002490683550292472
Current MSE: 0.5911015020602733
-0.0002471467486498957
Current MSE: 0.5908562288696448
-0.0002452731906285033
Current MSE: 0.590612782960131
-0.0002434459095138619
Current MSE: 0.5903711197574364
-0.0002416632026945864
Current MSE: 0.5901311963237408
-0.0002399234336956102
Current MSE: 0.5898929712941572
-0.00023822502958359415
Current MSE: 0.5896564048156829
-0.00023656647847425383
Current MSE: 0.5894214584885478
-0.00023494632713516594
Current MSE: 0.5891880953098604
-0.00023336317868738465
Current MSE: 0.5889562796194656
-0.00023181569039476546
Current MSE: 0.588725977047925
-0.0002303025715406637
Current MSE: 0.5884971544665357
-0.00022882258138923195
Current MSE: 0.5882697799393088
-0.00022737452722687568
Current MSE: 0.5880438226768292
-0.00022595726247964798
Current MSE: 0.5878192529919226
-0.0002245696849065837
Current MSE: 0.5875960422570599
-0.00022321073486275544
Current MSE: 0.5873741628634281
-0.0002218793936317187
Current MSE: 0.5871535881816055
-0.0002205746818226828
Current MSE: 0.586934292523774
-0.0002192956578314087
Current MSE: 0.586716251107412
-0.0002180414163620581
Current MSE: 0.5864994400204067
-0.0002168110870053308
Current MSE: 0.5862838361875307
-0.00021560383287599905
Current MSE: 0.5860694173382309
-0.00021441884929973565
Current MSE: 0.5858561619756757
-0.00021325536255523136
Current MSE: 0.585644049347012
-0.00021211262866371872
Current MSE: 0.5854330594147843
-0.0002109899322276787
Current MSE: 0.585223172829472
-0.0002098865853122911
Current MSE: 0.5850143709030962
-0.0002088019263758456
Current MSE: 0.5848066355838605
-0.00020773531923568012
Current MSE: 0.5845999494317792
-0.00020668615208130348
Current MSE: 0.5843942955952575
-0.0002056538365217131
Current MSE: 0.5841896577885863
-0.0002046378066711263
Current MSE: 0.5839860202703127
-0.00020363751827368048
Current MSE: 0.5837833678224558
-0.00020265244785688807
Current MSE: 0.5835816857305324
-0.00020168209192339415
Current MSE: 0.5833809597643598
-0.00020072596617259908
Current MSE: 0.5831811761596085
-0.000199783604751258
Current MSE: 0.5829823216000717
-0.00019885455953683184
Current MSE: 0.582784383200626
-0.00019793839944570735
Current MSE: 0.5825873484908551
-0.00019703470977083803
Current MSE: 0.5823912053993108
-0.00019614309154436516
Current MSE: 0.5821959422383864
-0.0001952631609243305
Current MSE: 0.5820015476897779
-0.00019439454860858962
Current MSE: 0.5818080107905104
-0.00019353689926748796
Current MSE: 0.5816153209195084
-0.0001926898710019609
Current MSE: 0.5814234677846869
-0.0001918531348215069
Current MSE: 0.5812324414105434
-0.000191026374143477
Current MSE: 0.5810422321262336
-0.00019020928430979467
Current MSE: 0.5808528305541069
-0.00018940157212676834
Current MSE: 0.5806642275986894
-0.00018860295541744954
Current MSE: 0.580476414436093
-0.00018781316259641745
Current MSE: 0.5802893825038342
-0.00018703193225877435
Current MSE: 0.5801031234910488
-0.0001862590127854613
Current MSE: 0.5799176293290845
-0.00018549416196422808
Current MSE: 0.5797328921824596
-0.0001847371466249248
Current MSE: 0.5795489044401685
-0.00018398774229111403
Current MSE: 0.5793656587073266
-0.00018324573284189682
Current MSE: 0.5791831477971368
-0.000182510910189837
Current MSE: 0.5790013647231668
-0.00018178307396998772
Current MSE: 0.5788203026919247
-0.00018106203124201858
Current MSE: 0.5786399550957217
-0.000180347596203001
Current MSE: 0.5784603155058097
-0.00017963958991207285
Current MSE: 0.5782813776657841
-0.00017893784002553925
Current MSE: 0.5781031354852421
-0.0001782421805420764
Current MSE: 0.5779255830336825
-0.00017755245155959276
Current MSE: 0.5777487145346436
-0.00017686849903886248
Current MSE: 0.5775725243600667
-0.00017619017457692898
Current MSE: 0.5773970070248727
-0.00017551733519394208
Current MSE: 0.5772221571817537
-0.00017484984311899598
Current MSE: 0.5770479696161589
-0.00017418756559484105
Current MSE: 0.5768744392414765
-0.00017353037468237353
Current MSE: 0.5767015610944006
-0.00017287814707589444
Current MSE: 0.5765293303304749
-0.00017223076392569592
Current MSE: 0.5763577422198072
-0.00017158811066775304
Current MSE: 0.5761867921429497
-0.0001709500768575234
Current MSE: 0.5760164755869361
-0.0001703165560135167
Current MSE: 0.5758467881414712
-0.00016968744546497216
Current MSE: 0.5756777254952645
-0.00016906264620664135
Current MSE: 0.5755092834325074
-0.0001684420627571237
Current MSE: 0.5753414578294823
-0.00016782560302508465
Current MSE: 0.575174244651302
-0.00016721317818035875
Current MSE: 0.5750076399487741
-0.00016660470252782833
Current MSE: 0.5748416398553847
-0.0001660000933894068
Current MSE: 0.5746762405843978
-0.0001653992709869101
Current MSE: 0.5745114384260631
-0.00016480215833469813
Current MSE: 0.5743472297449332
-0.00016420868112987375
Current MSE: 0.5741836109772813
-0.00016361876765191852
Current MSE: 0.5740205786286156
-0.00016303234866577032
Current MSE: 0.5738581292712914
-0.0001624493573241237
Current MSE: 0.5736962595422116
-0.0001618697290798332
Current MSE: 0.573534966140615
-0.0001612934015965406
Current MSE: 0.5733742458259486
-0.00016072031466640713
Current MSE: 0.5732140954158199
-0.00016015041012873432
Current MSE: 0.573054511784028
-0.00015958363179191526
Current MSE: 0.572895491858668
-0.00015901992536004883
Current MSE: 0.5727370326203074
-0.0001584592383605532
Current MSE: 0.5725791311002308
-0.00015790152007655323
Current MSE: 0.5724217843787522
-0.00015734672147860174
Current MSE: 0.5722649895835898
-0.00015679479516239603
Current MSE: 0.5721087438883022
-0.00015624569528760457
Current MSE: 0.5719530445107825
-0.00015569937751969132
Current MSE: 0.571797888711812
-0.0001551557989705188
Current MSE: 0.571643273793664
-0.00015461491814805495
Current MSE: 0.5714891970987636
-0.00015407669490041798
Current MSE: 0.5713356560083949
-0.0001535410903686918
Current MSE: 0.5711826479414597
-0.00015300806693518965
Current MSE: 0.5710301703532785
-0.00015247758818115464
Current MSE: 0.5708782207344409
-0.00015194961883757685
Current MSE: 0.5707267966096943
-0.00015142412474666855
Current MSE: 0.5705758955368782
-0.00015090107281612308
Current MSE: 0.5704255151058946
-0.00015038043098358767
Current MSE: 0.5702756529377193
-0.0001498621681752521
Current MSE: 0.5701263066834488
-0.0001493462542705437
Current MSE: 0.5699774740233816
-0.00014883266006715523
Current MSE: 0.569829152666136
-0.00014832135724562878
Current MSE: 0.5696813403477977
-0.00014781231833826958
Current MSE: 0.5695340348311011
-0.0001473055166966164
Current MSE: 0.5693872339046396
-0.00014680092646146559
Current MSE: 0.5692409353821047
-0.0001462985225348934
Current MSE: 0.5690951371015548
-0.00014579828054994692
Current MSE: 0.5689498369247089
-0.00014530017684588614
Current MSE: 0.5688050327362669
-0.00014480418844198262
Current MSE: 0.5686607224432554
-0.0001443102930115403
Current MSE: 0.5685169039743968
-0.00014381846885858085
Current MSE: 0.5683735752795006
-0.00014332869489619426
Current MSE: 0.5682307343288792
-0.00014284095062144786
Current MSE: 0.5680883791127824
-0.00014235521609673452
Current MSE: 0.567946507640854
-0.0001418714719284564
Current MSE: 0.5678051179416076
-0.0001413896992463748
Current MSE: 0.5676642080619207
-0.00014090987968684576
Current MSE: 0.5675237760665491
-0.00014043199537161488
Current MSE: 0.5673838200376563
-0.0001399560288928292
Current MSE: 0.567244338074361
-0.00013948196329527374
Current MSE: 0.5671053282923018
-0.00013900978205927395
Current MSE: 0.5669667888232147
-0.00013853946908704007
Current MSE: 0.5668287178145296
-0.00013807100868512556
Current MSE: 0.5666911134289775
-0.00013760438555210364
Current MSE: 0.5665539738442138
-0.00013713958476369026
Current MSE: 0.566417297252454
-0.00013667659175975455
Current MSE: 0.5662810818601238
-0.00013621539233021895
Current MSE: 0.5661453258875189
-0.0001357559726049562
Current MSE: 0.56601002756848
-0.00013529831903891232
Current MSE: 0.5658751851500758
-0.00013484241840411304
Current MSE: 0.565740796892301
-0.00013438825777489782
Current MSE: 0.5656068610677806

In [18]:
SR.err_sq

np.float64(0.5554138826727365)

In [19]:
x_test_scaled = scalar.transform(x_test)
x_test_scaled

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
2,1.785329,1.853666,1.255454,-0.046076,-0.811544,-0.034658,1.037737,-1.334675
8,-0.934255,1.057132,-0.484454,0.050633,-0.189895,-0.152467,1.033059,-1.344665
12,-0.411771,1.853666,-0.036396,-0.178721,-0.284456,-0.103958,1.037737,-1.344665
13,-0.622635,1.853666,-0.612580,0.006992,-0.943754,-0.159172,1.033059,-1.344665
15,-0.910825,1.694359,-0.506973,-0.049306,-0.635556,-0.059289,1.037737,-1.344665
...,...,...,...,...,...,...,...,...
20623,-0.543889,0.260599,-0.132813,-0.042917,-0.722237,-0.060169,1.589785,-0.900112
20627,-0.451170,-1.890041,0.288211,0.015731,-1.097853,-0.025216,1.636568,-0.875137
20629,-0.926953,-0.058014,0.049489,-0.161039,4.806062,0.117238,1.631890,-0.910102
20630,-0.153156,-1.412121,0.229308,0.088231,-0.145242,-0.031246,1.711422,-0.875137
20635,-1.207474,-0.296974,-0.157150,0.084954,-0.505973,-0.071375,1.800311,-0.760253

In [20]:
y_cap = SR.predict(x_test_scaled)
y_cap

2        3.777823
8        1.651470
12       2.135382
13       2.043452
15       1.759594
           ...
20623    1.314445
20627    0.912430
20629    1.028455
20630    1.251900
20635    0.537001
Length: 6192, dtype: float64

In [21]:
y_train

4553     3.500
12286    0.550
17333    2.268
17442    1.352
9628     0.875
         ...
12618    1.836
6356     1.796
10615    3.291
18600    2.841
4134     1.781
Name: MedHouseVal, Length: 14448, dtype: float64

In [22]:
y_cap

2        3.777823
8        1.651470
12       2.135382
13       2.043452
15       1.759594
           ...
20623    1.314445
20627    0.912430
20629    1.028455
20630    1.251900
20635    0.537001
Length: 6192, dtype: float64

In [23]:
import numpy as np
err = y_cap - y_test
err_sq = np.square(err)

In [24]:
err_sq.sum()/x_test.shape[0]

np.float64(0.5618643997220508)

In [25]:
from sklearn.linear_model import LinearRegression
model_sk = LinearRegression()

In [26]:
model_sk.fit(x_train_scaled, y_train)

LinearRegression()

In [27]:
model_sk.score(x_train_scaled, y_train)

0.6083938750059538

In [28]:
y_cap_sk = model_sk.predict(x_test_scaled)

In [29]:
model_sk.score(x_test_scaled, y_test)

0.5988242922202462

In [30]:
y_cap_sk_tr = model_sk.predict(x_train_scaled)

In [31]:
err_sk_tr = np.square(y_cap_sk_tr - y_train)
mse = np.sum(err_sk_tr)/x_train_scaled.shape[0]
mse

np.float64(0.5240406542274328)

In [32]:
err_ts = np.square(y_cap_sk - y_test)
mse_ts = np.sum(err_ts)/x_test_scaled.shape[0]
mse_ts

np.float64(0.5279016118390674)

In [33]:
a = np.array([1,2,3,4]) 
b = np.array([2,3,4,5])

In [34]:
pd.DataFrame({'A': a,'B': b})

   A  B
0  1  2
1  2  3
2  3  4
3  4  5