In [8]:
import sys
sys.path.append('..')

In [ ]:
import pandas as pd
from models.Regression import StandardScaler, TrainTestSplit, LogisticRegression
import numpy as np

In [10]:
df = pd.read_csv('../data/Telco_Customer_Churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [11]:
x = df.drop('Churn', axis=1)
x

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5

In [12]:
y = df['Churn']
y

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: str

In [13]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [14]:
df_encoded = pd.get_dummies(df, columns = ['StreamingMovies', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'Contract', 'PaymentMethod'], drop_first=True)
df_encoded = df_encoded.replace('No',0).replace('Yes',1)
df_encoded = df_encoded.replace(True, 1).replace(False, 0)
df_encoded

,customerID,SeniorCitizen,tenure,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,StreamingMovies_No internet service,StreamingMovies_Yes,gender_Male,...,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,1,1,29.85,29.85,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,5575-GNVDE,0,34,0,56.95,1889.5,0,0,0,1,...,1,0,0,0,0,1,0,0,0,1
2,3668-QPYBK,0,2,1,53.85,108.15,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
3,7795-CFOCW,0,45,0,42.30,1840.75,0,0,0,1,...,1,0,1,0,0,1,0,0,0,0
4,9237-HQITU,0,2,1,70.70,151.65,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,24,1,84.80,1990.5,0,0,1,1,...,1,0,1,0,1,1,0,0,0,1
7039,2234-XADUH,0,72,1,103.20,7362.9,0,0,1,0,...,1,0,0,0,1,1,0,1,0,0
7040,4801-JZAZL,0,11,1,29.60,346.45,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
7041,8361-LTMKD,1,4,1,74.40,306.6,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
7042,3186-AJIEK,0,66,1,105.65,6844.5,0,0,1,1,...,1,0,1,0,1,0,1,0,0,0

In [15]:
df_encoded.drop(['customerID'], axis=1, inplace=True)

In [16]:
df_encoded

,SeniorCitizen,tenure,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,StreamingMovies_No internet service,StreamingMovies_Yes,gender_Male,Partner_Yes,...,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,1,29.85,29.85,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1,0,34,0,56.95,1889.5,0,0,0,1,0,...,1,0,0,0,0,1,0,0,0,1
2,0,2,1,53.85,108.15,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
3,0,45,0,42.30,1840.75,0,0,0,1,0,...,1,0,1,0,0,1,0,0,0,0
4,0,2,1,70.70,151.65,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,1,84.80,1990.5,0,0,1,1,1,...,1,0,1,0,1,1,0,0,0,1
7039,0,72,1,103.20,7362.9,0,0,1,0,1,...,1,0,0,0,1,1,0,1,0,0
7040,0,11,1,29.60,346.45,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
7041,1,4,1,74.40,306.6,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,1
7042,0,66,1,105.65,6844.5,0,0,1,1,0,...,1,0,1,0,1,0,1,0,0,0

In [17]:
x = df_encoded.drop('Churn', axis=1)
y = pd.get_dummies(df_encoded['Churn'], drop_first=True)

In [18]:
x.loc[x['TotalCharges']==' ', 'TotalCharges'] = '0'
x[x['TotalCharges']==' ']

Empty DataFrame
Columns: [SeniorCitizen, tenure, PaperlessBilling, MonthlyCharges, TotalCharges, StreamingMovies_No internet service, StreamingMovies_Yes, gender_Male, Partner_Yes, Dependents_Yes, PhoneService_Yes, MultipleLines_No phone service, MultipleLines_Yes, InternetService_Fiber optic, InternetService_No, OnlineSecurity_No internet service, OnlineSecurity_Yes, OnlineBackup_No internet service, OnlineBackup_Yes, DeviceProtection_No internet service, DeviceProtection_Yes, TechSupport_No internet service, TechSupport_Yes, StreamingTV_No internet service, StreamingTV_Yes, Contract_One year, Contract_Two year, PaymentMethod_Credit card (automatic), PaymentMethod_Electronic check, PaymentMethod_Mailed check]
Index: []

[0 rows x 30 columns]

In [19]:
x['TotalCharges'] = x['TotalCharges'].astype(float)
x['TotalCharges']

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [20]:
for c in x.columns:
    if x[c].dtype=='object':
        x[c] = x[c].astype(int)

In [21]:
y

          1
0     False
1     False
2      True
3     False
4      True
...     ...
7038  False
7039  False
7040  False
7041   True
7042  False

[7043 rows x 1 columns]

In [22]:
y = pd.Series([1 if x==True else 0 for x in y[1]])
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Length: 7043, dtype: int64

In [23]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Length: 7043, dtype: int64

In [24]:
split = TrainTestSplit()
x_train, y_train, x_test, y_test = split.split(x, y)
x_train

,SeniorCitizen,tenure,PaperlessBilling,MonthlyCharges,TotalCharges,StreamingMovies_No internet service,StreamingMovies_Yes,gender_Male,Partner_Yes,Dependents_Yes,...,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
2620,0,18,1,68.35,1299.80,0,0,1,0,0,...,1,0,1,0,1,0,0,0,1,0
6282,0,4,0,19.55,68.80,1,0,1,1,1,...,0,1,0,1,0,0,1,1,0,0
345,1,1,1,72.10,72.10,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5526,0,51,1,23.95,1216.35,1,0,1,1,1,...,0,1,0,1,0,1,0,0,0,1
3263,0,52,0,85.80,4433.30,0,0,0,1,1,...,1,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,0,15,0,19.40,289.30,1,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
4282,0,52,0,101.25,5301.10,0,1,0,1,1,...,1,0,0,0,1,1,0,0,0,0
1299,0,11,1,44.05,483.70,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1467,0,23,1,73.75,1756.60,0,1,0,0,0,...,0,0,1,0,1,1,0,0,0,1
6913,0,69,1,108.75,7493.05,0,1,0,1,1,...,1,0,1,0,1,1,0,0,0,0

In [25]:
x_test

,SeniorCitizen,tenure,PaperlessBilling,MonthlyCharges,TotalCharges,StreamingMovies_No internet service,StreamingMovies_Yes,gender_Male,Partner_Yes,Dependents_Yes,...,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
4,0,2,1,70.70,151.65,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5,0,8,1,99.65,820.50,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
10,0,13,1,49.95,587.45,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1
11,0,16,0,18.95,326.80,1,0,1,0,0,...,0,1,0,1,0,0,1,1,0,0
16,0,52,0,20.65,1022.95,1,0,0,0,0,...,0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7029,1,6,1,44.40,263.05,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
7031,1,55,0,60.00,3316.10,0,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
7032,1,1,1,75.75,75.75,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
7035,0,19,1,78.70,1495.10,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
7042,0,66,1,105.65,6844.50,0,1,1,0,0,...,1,0,1,0,1,0,1,0,0,0

In [26]:
y_train

2620    0
6282    0
345     0
5526    0
3263    0
       ..
1244    1
4282    0
1299    1
1467    0
6913    0
Length: 4931, dtype: int64

In [27]:
y_test

4       1
5       1
10      0
11      0
16      0
       ..
7029    0
7031    0
7032    1
7035    0
7042    0
Length: 2112, dtype: int64

In [28]:
for c in x.columns:
    print(f'{c}: {x[c].dtype}')

SeniorCitizen: int64
tenure: int64
PaperlessBilling: int64
MonthlyCharges: float64
TotalCharges: float64
StreamingMovies_No internet service: int64
StreamingMovies_Yes: int64
gender_Male: int64
Partner_Yes: int64
Dependents_Yes: int64
PhoneService_Yes: int64
MultipleLines_No phone service: int64
MultipleLines_Yes: int64
InternetService_Fiber optic: int64
InternetService_No: int64
OnlineSecurity_No internet service: int64
OnlineSecurity_Yes: int64
OnlineBackup_No internet service: int64
OnlineBackup_Yes: int64
DeviceProtection_No internet service: int64
DeviceProtection_Yes: int64
TechSupport_No internet service: int64
TechSupport_Yes: int64
StreamingTV_No internet service: int64
StreamingTV_Yes: int64
Contract_One year: int64
Contract_Two year: int64
PaymentMethod_Credit card (automatic): int64
PaymentMethod_Electronic check: int64
PaymentMethod_Mailed check: int64

In [29]:
scaler = StandardScaler()
x_train_scaled = scaler.fit(x_train)

In [30]:
lr = LogisticRegression()
lr.fit(x_train_scaled, y_train)

0.6931471805599455
-0.0026660791118514604
-0.0026075733453947425
-0.0025510700115323193
-0.0024964912264517913
-0.0024437615564120163
-0.0023928080406516727
-0.002343560199094319
-0.002295950026724114
-0.0022499119763443876
-0.002205382931314337
-0.002162302169711361
-0.0021206113212390854
-0.0020802543180806765
-0.0020411773407745804
-0.0020033287600795813
-0.0019666590756932667
-0.0019311208525903956
-0.0018966686556570744
-0.0018632589832191515
-0.0018308501999811932
-0.0017994024698290145
-0.0017688776888857838
-0.0017392394191526606
-0.0017104528230188487
-0.0016824845988768766
-0.001655302918040058
-0.0016288773631233378
-0.0016031788680170855
-0.0015781796595537578
-0.0015538532009448103
-0.0015301741370424837
-0.0015071182414598816
-0.0014846623655757618
-0.001462784389422267
-0.0014414631744535944
-0.001420678518180507
-0.0014004111106424855
-0.0013806424926885441
-0.001361355016027077
-0.0013425318050066526
-0.001324156720072911
-0.0013062143228650402
-0.0012886898428878801
-0.001271569145717355
-0.001254838702678951
-0.001238485561947944
-0.001222497321017979
-0.001206862100480821
-0.00119156851906832
-0.0011766056698985228
-0.0011619630978815243
-0.0011476307782263273
-0.0011335990960072984
-0.001119858826735376
-0.0011064011178951727
-0.0010932174713953469
-0.0010802997268961612
-0.001067640045965046
-0.0010552308970301905
-0.0010430650410804265
-0.0010311355180883108
-0.0010194356341093336
-0.0010079589490311625
-0.000996699264936396
-0.000985650615050404
-0.0009748072532407281
-0.0009641636440467227
-0.0009537144532039132
-0.0009434545386458604
-0.0009333789419524452
-0.0009234828802264783
-0.0009137617383732088
-0.0009042110617631938
-0.0008948265492590979
-0.0008856040465866633
-0.0008765395400323062
-0.0008676291504501332
-0.0008588691275632776
-0.0008502558445423469
-0.0008417857928488814
-0.000833455577327169
-0.0008252619115353133
-0.0008172016132991233
-0.0008092716004797218
-0.0008014688869431019
-0.0007937905787217536
-0.0007862338703568117
-0.0007787960414129547
-0.0007714744531565065
-0.0007642665453893027
-0.0007571698334277732
-0.00075018190522258
-0.000743300418610926
-0.0007365230986932092
-0.0007298477353292476
-0.0007232721807477471
-0.0007167943472639049
-0.0007104122050960449
-0.0007041237802832834
-0.0006979271526916797
-0.0006918204541087603
-0.0006858018664216425
-0.0006798696198738741
-0.0006740219913955459
-0.000668257303008013
-0.000662573920292564
-0.0006569702509260367
-0.0006514447432777182
-0.0006459958850626446
-0.000640622202052965
-0.0006353222568393768
-0.0006300946476467395
-0.0006249380071919886
-0.0006198510015943404
-0.000614832329323578
-0.0006098807201917467
-0.0006049949343862604
-0.0006001737615367597
-0.0005954160198217151
-0.0005907205551070049
-0.0005860862401174671
-0.0005815119736412022
-0.0005769966797615211
-0.000572539307119424
-0.0005681388282021693
-0.000563794238657267
-0.0005595045566328949
-0.0005552688221411861
-0.0005510860964443864
-0.0005469554614627725
-0.0005428760192026649
-0.0005388468912060906
-0.000534867218017987
-0.0005309361586719463
-0.0005270528901946125
-0.0005232166071241773
-0.0005194265210487492
-0.0005156818601569357
-0.000511981868804523
-0.0005083258070948116
-0.0005047129504747172
-0.0005011425893394206
-0.0004976140286552244
-0.0004941265875889611
-0.0004906795991539425
-0.00048727240986290443
-0.00048390437939493935
-0.00048057488026975737
-0.0004772832975347141
-0.0004740290284596105
-0.0004708114822404852
-0.00046763007971351023
-0.0004644842530764359
-0.00046137344561858473
-0.0004582971114589496
-0.0004552547152907316
-0.0004522457321353146
-0.0004492696471009028
-0.00044632595515026185
-0.0004434141608737896
-0.0004405337782673602
-0.0004376843305216038
-0.0004348653498100763
-0.00043207637708864155
-0.00042931696189829616
-0.00042658666217221253
-0.00042388504405121985
-0.00042121168169984013
-0.0004185661571319832
-0.00041594806003719675
-0.000413356987614133
-0.00041079254440623547
-0.00040825434214519785
-0.00040574199959286794
-0.00040325514239336613
-0.00040079340292487053
-0.0003983564201560652
-0.0003959438395072512
-0.00039355531271412225
-0.000391190497694871
-0.00038884905842040407
-0.0003865306647892197
-0.00038423499250317406
-0.00038196172294791
-0.0003797105430762837
-0.0003774811452925686
-0.00037527322734232094
-0.00037308649220257895
-0.00037092064797572544
-0.0003687754077867922
-0.0003666504896796541
-0.00036454561652121686
-0.00036246051590183015
-0.00036039492004402707
-0.00035834856570637896
-0.0003563211940978972
-0.00035431255078655077
-0.00035232238561477836
-0.0003503504526158885
-0.0003483965099309039
-0.0003464603197289584
-0.0003445416481289154
-0.0003426402651225402
-0.000340755944499449
-0.0003388884637738343
-0.00033703760411341044
-0.0003352031502684705
-0.00033338489050371845
-0.000331582616531767
-0.00032979612344674614
-0.0003280252096602432
-0.0003262696768397966
-0.00032452932984572413
-0.0003228039766722812
-0.0003210934283885969
-0.0003193974990811643
-0.0003177160057974415
-0.0003160487684906732
-0.0003143956099667111
-0.00031275635583016825
-0.00031113083443334855
-0.0003095188768260648
-0.0003079203167053457
-0.0003063349903668078
-0.00030476273665902553
-0.0003032033969339043
-0.00030165681500404773
-0.00030012283709734966
-0.00029860131181180805
-0.00029709209007466875
-0.000295595025100015
-0.0002941099723472451
-0.00029263678948088234
-0.0002911753363317171
-0.00028972547485817124
-0.00028828706910777324
-0.0002868599851805209
-0.00028544409119291014
-0.0002840392572420747
-0.0002826453553704811
-0.0002812622595323999
-0.0002798898455598775
-0.0002785279911307059
-0.00027717657573478327
-0.00027583548064408214
-0.00027450458888089724
-0.0002731837851877028
-0.0002718729559970101
-0.00027057198940322325
-0.00026928077513277415
-0.0002679992045171442
-0.00026672717046472005
-0.00026546456743420377
-0.00026421129140774546
-0.0002629672398656302
-0.00026173231176024325
-0.00026050640749131215
-0.00025928942888192585
-0.0002580812791534992
-0.00025688186290329096
-0.0002556910860805339
-0.0002545088559643971
-0.0002533350811410595
-0.00025216967148222746
-0.0002510125381243733
-0.00024986359344647546
-0.00024872275105009
-0.00024758992573942207
-0.0002464650335010643
-0.0002453479914842349
-0.0002442387179824035
-0.00024313713241402857
-0.000242043155304128
-0.0002409567082666264
-0.00023987771398586988
-0.00023880609620008375
-0.0002377417796836645
-0.00023668469023063743
-0.00023563475463783679
-0.0002345919006896402
-0.0002335560571407047
-0.00023252715370181143
-0.00023150512102343423
-0.00023048989068119585
-0.00022948139516143495
-0.000228479567845552
-0.00022748434299763032
-0.00022649565574828223
-0.0002255134420828253
-0.00022453763882662736
-0.00022356818363206132
-0.0002226050149662373
-0.00022164807209695825
-0.00022069729508156222
-0.00021975262475304458
-0.00021881400270984397
-0.00021788137130185348
-0.00021695467362059517
-0.00021603385348645254
-0.00021511885543812337
-0.0002142096247210734
-0.0002133061072769893
-0.0002124082497330093
-0.00021151599939106536
-0.00021062930421744674
-0.00020974811283325234
-0.0002088723745036769
-0.0002080020391287407
-0.00020713705723324205
-0.00020627737995781992
-0.0002054229590489065
-0.00020457374685056706
-0.00020372969629423032
-0.00020289076089152758
-0.00020205689472369004
-0.00020122805243455444
-0.00020040418922173675
-0.0001995852608277504
-0.00019877122353262333
-0.00019796203414601532
-0.00019715764999866936
-0.00019635802893513965
-0.00019556312930651965
-0.00019477290996233743
-0.00019398733024383885
-0.00019320634997599395
-0.00019242992946177928
-0.0001916580294735737
-0.0001908906112475517
-0.000190127636476356
-0.00018936906730282477
-0.00018861486631294166
-0.00018786499653011823
-0.00018711942140836602
-0.0001863781048265789
-0.00018564101108164976
-0.00018490810488358544
-0.00018417935134840135
-0.00018345471599368057
-0.0001827341647314129
-0.000182017663863554
-0.00018130518007597463
-0.00018059668043296506
-0.00017989213237229462
-0.0001791915036995495
-0.00017849476258297026
-0.00017780187754895538
-0.00017711281747628815
-0.00017642755159169576
-0.00017574604946468675
-0.00017506828100316563
-0.00017439421644838138
-0.0001737238263707086
-0.00017305708166437395
-0.00017239395354406994
-0.0001717344135395149
-0.00017107843349167817
-0.0001704259855487278
-0.000169777042160979
-0.0001691315760777301
-0.000168489560342433
-0.00016785096828964008
-0.00016721577353961958
-0.00016658394999607973
-0.00016595547184128367
-0.00016533031353244132
-0.0001647084497987672
-0.00016408985563642897
-0.0001634745063068821
-0.00016286237733104114
-0.00016225344448816958
-0.00016164768381055072
-0.00016104507158115622
-0.00016044558433037093
-0.00015984919883182958
-0.00015925589210036284
-0.00015866564138800054
-0.0001580784241811961
-0.00015749421819777343
-0.00015691300138370723
-0.00015633475191045854
-0.00015575944817181053
-0.00015518706878070443
-0.0001546175925674631
-0.00015405099857546123
-0.0001534872660597375
-0.00015292637448355295
-0.0001523683035157264
-0.00015181303302841398
-0.0001512605430940006
-0.00015071081398299047
-0.00015016382616123147
-0.00014961956028763934
-0.00014907799721125548
-0.00014853911796963715
-0.00014800290378574887
-0.00014746933606607504
-0.0001469383963981774
-0.00014641006654853017
-0.00014588432845974442
-0.00014536116424934686
-0.0001448405562069488
-0.00014432248679174808
-0.00014380693863158545
-0.0001432938945199469
-0.00014278333741396532
-0.00014227525043269962
-0.00014176961685524736
-0.00014126642011835777
-0.00014076564381487744
-0.0001402672716916964
-0.00013977128764786073
-0.00013927767573268524
-0.00013878642014414355
-0.00013829750522681428
-0.00013781091547043767
-0.0001373266355076952
-0.00013684465011293279
-0.00013636494420016243
-0.00013588750282195194
-0.00013541231116670494
-0.0001349393545581612
-0.00013446861845323177
-0.00013400008844038913
-0.00013353375023844594
-0.00013306958969477867
-0.00013260759278344025
-0.00013214774560499354
-0.0001316900343831251
-0.0001312344454648673
-0.00013078096531832228
-0.00013032958053132981
-0.00012988027781035694
-0.00012943304397894373
-0.00012898786597626
-0.00012854473085605056
-0.0001281036257849144
-0.00012766453804147204
-0.00012722745501481114
-0.00012679236420320983
-0.00012635925321313746
-0.00012592810975753377
-0.0001254989216553648
-0.0001250716768296245
-0.00012464636330661305
-0.00012422296921477116
-0.00012380148278351433
-0.00012338189234173402
-0.0001229641863172981
-0.00012254835323566304
-0.0001221343817184306
-0.00012172226048284829
-0.00012131197834064356
-0.00012090352419680261
-0.00012049688704818262
-0.00012009205598351169
-0.00011968902018166805
-0.00011928776891045878
-0.0001188882915263978
-0.00011849057747320701
-0.00011809461628103923
-0.00011770039756553441
-0.00011730791102682048
-0.0001169171464487917
-0.00011652809369794292
-0.00011614074272275898
-0.00011575508355254893
-0.00011537110629689096
-0.00011498880114457766
-0.00011460815836272786
-0.00011422916829628704
-0.00011385182136663952
-0.00011347610807138642
-0.00011310201898329098
-0.00011272954474927932
-0.00011235867608999639
-0.00011198940379902877
-0.0001116217187417945
-0.00011125561185532096
-0.00011089107414685717
-0.00011052809669370722
-0.00011016667064245311
-0.00010980678720784454
-0.00010944843767229928
-0.00010909161338545914
-0.00010873630576335724
-0.00010838250628725232
-0.00010803020650390627
-0.00010767939802425186
-0.00010733007252261562
-0.00010698222173666228
-0.00010663583746650662
-0.0001062909115737698
-0.00010594743598146827
-0.00010560540267284813
-0.00010526480369171809
-0.00010492563114039566
-0.00010458787718059526
-0.00010425153403198495
-0.00010391659397185338
-0.00010358304933422158
-0.00010325089251017605
-0.00010292011594636996
-0.00010259071214457904
-0.00010226267366186814
-0.00010193599310942547
-0.00010161066315206302
-0.0001012866765079945
-0.00010096402594811371
-0.00010064270429555044
-0.00010032270442517088
-0.00010000401926291147
-9.968664178561237e-05
Accuracy: 0.7982153721354694
Precision: 0.6043010752688172
Recall: 0.6555209953343701
F1: 0.6288698246922789

(np.float64(0.7982153721354694),
 np.float64(0.6043010752688172),
 np.float64(0.6555209953343701),
 np.float64(0.6288698246922789))

In [31]:
x_test_scaled = scaler.transform(x_test)

In [32]:
y_cap = lr.predict_class(x_test_scaled)
y_cap

[1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 ...]

In [33]:
lr.model_accuracy(y_cap, y_test)

Accuracy: 0.7850378787878788
Precision: 0.6028708133971292
Recall: 0.6483704974271012
F1: 0.6247933884297521

(np.float64(0.7850378787878788),
 np.float64(0.6028708133971292),
 np.float64(0.6483704974271012),
 np.float64(0.6247933884297521))

In [34]:
from sklearn.linear_model import LogisticRegression
lr_sk = LogisticRegression()
lr_sk.fit(x_train_scaled, y_train)

LogisticRegression()

In [35]:
y_tr = lr_sk.predict(x_train_scaled)

In [36]:
lr_sk.score(x_train_scaled, y_train)

0.809774893530724

In [37]:
y_ts = lr_sk.predict(x_test_scaled)

In [38]:
lr_sk.score(x_test_scaled, y_test)

0.7940340909090909

In [39]:
y_train.value_counts()

0    3645
1    1286
Name: count, dtype: int64